spring:
  datasource:
    url: jdbc:mysql://120.79.222.252:3306/test
    username: root
    password: 123456
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      minimum-idle: 5
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: update