spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://120.79.222.252:3306/javashop
    driver-class-name: com.mysql.jdbc.Driver
  http:
    encoding:
      charset: utf-8
      enabled: true
mybatis:
  type-aliases-package: com.developlee.mybatispagehelper.domain
  mapper-locations: classpath:/mapper/*.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

